// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC03RoRnso1ZmoRgZwus2Pc1ZbIV1BT4tM',
    appId: '1:701176046399:web:2c1ab97f554e473e72e98a',
    messagingSenderId: '701176046399',
    projectId: 'virtual-wardrobe-70879',
    authDomain: 'virtual-wardrobe-70879.firebaseapp.com',
    storageBucket: 'virtual-wardrobe-70879.firebasestorage.app',
    measurementId: 'G-1Y930WW8GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4o6aS3TBx_y5xaeiIWVhqoOzkCePySio',
    appId: '1:701176046399:android:a01337826861fa8972e98a',
    messagingSenderId: '701176046399',
    projectId: 'virtual-wardrobe-70879',
    storageBucket: 'virtual-wardrobe-70879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUcNUqEJHu9N224FeRJev_K4yP2qM4GcE',
    appId: '1:701176046399:ios:5751e71085f3348172e98a',
    messagingSenderId: '701176046399',
    projectId: 'virtual-wardrobe-70879',
    storageBucket: 'virtual-wardrobe-70879.firebasestorage.app',
    iosBundleId: 'com.example.virtualWardrobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUcNUqEJHu9N224FeRJev_K4yP2qM4GcE',
    appId: '1:701176046399:ios:5751e71085f3348172e98a',
    messagingSenderId: '701176046399',
    projectId: 'virtual-wardrobe-70879',
    storageBucket: 'virtual-wardrobe-70879.firebasestorage.app',
    iosBundleId: 'com.example.virtualWardrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC03RoRnso1ZmoRgZwus2Pc1ZbIV1BT4tM',
    appId: '1:701176046399:web:852b29054af8e6a072e98a',
    messagingSenderId: '701176046399',
    projectId: 'virtual-wardrobe-70879',
    authDomain: 'virtual-wardrobe-70879.firebaseapp.com',
    storageBucket: 'virtual-wardrobe-70879.firebasestorage.app',
    measurementId: 'G-ZJBJ8P06CL',
  );
}
